version: '3.7'

services:
  postgres:
    restart: always
    image: postgres:11.4
    ports:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  web:
    restart: always
    build:
      context: web
      target: developer
    ports:
      - "8006:8000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/usr/src/app
      - ./data:/usr/src/app/data
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    env_file: .env

volumes:
  pgdata:
