# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 04:20
from __future__ import unicode_literals

from django.db import migrations


_data = [
    {'name': 'Депутаты ЖК', 'slug': 'bishkek'},
    {'name': '', 'slug': 'bishkek'},
]


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city'),
    ]

    def qwerty(apps, schema_editor):
        City = apps.get_model('account', 'Position')

        for x in _data:
            City.objects.get_or_create(city_id=x['id'], slug=x['slug'], name=x['name'])

    def revert(apps, scema):
        pass

    operations = [
        migrations.RunPython(qwerty, revert),
    ]
