# Generated by Django 2.2 on 2020-04-29 12:58

from django.db import migrations, models
import party.vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200303_0503'),
        ('vote', '0003_auto_20200303_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=party.vote.models.question_directory_path, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='question',
            name='observer_position',
            field=models.ManyToManyField(related_name='question_text_observer_position', to='account.Position', verbose_name='Наблюдатель'),
        ),
        migrations.AddField(
            model_name='question',
            name='voter_position',
            field=models.ManyToManyField(related_name='question_text_voter_position', to='account.Position', verbose_name='Голосователь'),
        ),
    ]
