# Generated by Django 2.2 on 2020-05-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20200429_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='project_date',
        ),
    ]
