# Generated by Django 2.2 on 2020-01-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventdiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_personal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
