# Generated by Django 2.2 on 2020-03-03 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_is_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('datetime',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventdiscussion',
            options={'ordering': ('-created',), 'verbose_name': 'Дискуссия мероприятия', 'verbose_name_plural': 'Дискуссии мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('-date',), 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_personal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Личное'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='место расположения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число людей'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='eventdiscussion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='eventdiscussion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='event.Event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventdiscussion',
            name='message',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='eventdiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_discussions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.Event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
