# Generated by Django 2.2 on 2019-12-30 04:26

from django.db import migrations, models
import party.post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='picture',
        ),
        migrations.AddField(
            model_name='postimages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=party.post.models.PostImages.user_directory_path),
        ),
        migrations.AddField(
            model_name='postimages',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=50),
        ),
    ]
