# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 04:20
from __future__ import unicode_literals

from django.db import migrations


_data = {
    'regions': [
        {'name': 'Баткенская область', 'slug': 'batkenskaya-oblast', 'id': 2},
        {'name': 'Чуйская область', 'slug': 'chuyskaya-oblast', 'id': 3},
        {'name': 'Джалал-Абадская область', 'slug': 'dzhalal-abadskaya-oblast', 'id': 4},
        {'name': 'Нарынская область', 'slug': 'narynskaya-oblast', 'id': 5},
        {'name': 'Ошская область', 'slug': 'oshskaya-oblast', 'id': 6},
        {'name': 'Таласская область', 'slug': 'talasskaya-oblast', 'id': 7},
        {'name': 'Иссык-Кульская область', 'slug': 'issyk-kulskaya-oblast', 'id': 8},
    ],
    'district': [
        {'name': 'Первомайский район', 'slug': 'pervomayskiy-rayon', 'id': 1},
        {'name': 'Свердловский район', 'slug': 'sverdlovskiy-rayon', 'id': 2},
        {'name': 'Октябрьский район', 'slug': 'oktyabrskiy-rayon', 'id': 3},
        {'name': 'Ленинский район', 'slug': 'leninskiy-rayon', 'id': 4},
    ]
}


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    def qwerty(apps, schema_editor):
        Region = apps.get_model('locations', 'Region')
        District = apps.get_model('locations', 'District')

        for x in _data['regions']:
            Region.objects.get_or_create(region_id=x['id'], slug=x['slug'], name=x['name'])

        for x in _data['district']:
            District.objects.get_or_create(district_id=x['id'], slug=x['slug'], name=x['name'])


    def revert(apps, scema):
        pass

    operations = [
        migrations.RunPython(qwerty, revert),
    ]
