# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 04:20
from __future__ import unicode_literals

from django.db import migrations


_data = {
    'regions': [
        {'name': 'Бишкек', 'slug': 'bishkek', 'id': 1},
        {'name': 'Баткенская область', 'slug': 'batkenskaya-oblast', 'id': 2},
        {'name': 'Чуйская область', 'slug': 'chuyskaya-oblast', 'id': 3},
        {'name': 'Джалал-Абадская область', 'slug': 'dzhalal-abadskaya-oblast', 'id': 4},
        {'name': 'Нарынская область', 'slug': 'narynskaya-oblast', 'id': 5},
        {'name': 'Ошская область', 'slug': 'oshskaya-oblast', 'id': 6},
        {'name': 'Таласская область', 'slug': 'talasskaya-oblast', 'id': 7},
        {'name': 'Иссык-Кульская область', 'slug': 'issyk-kulskaya-oblast', 'id': 8},
        {'name': 'Ош', 'slug': 'osh', 'id': 9},
    ],
    'district': [
        {'name': 'Первомайский район', 'slug': 'pervomayskiy-rayon', 'id': 1},
        {'name': 'Свердловский район', 'slug': 'sverdlovskiy-rayon', 'id': 2},
        {'name': 'Октябрьский район', 'slug': 'oktyabrskiy-rayon', 'id': 3},
        {'name': 'Ленинский район', 'slug': 'leninskiy-rayon', 'id': 4},
        {'name': '3 мкр', 'slug': '3_mkr', 'id': 6},
        {'name': '4 мкр', 'slug': '4_mkr', 'id': 7},
        {'name': '5 мкр', 'slug': '5_mkr', 'id': 8},
        {'name': '6 мкр', 'slug': '6_mkr', 'id': 9},
        {'name': '7 мкр', 'slug': '7_mkr', 'id': 10},
        {'name': '8 мкр', 'slug': '8_mkr', 'id': 11},
        {'name': '9 мкр', 'slug': '9_mkr', 'id': 12},
        {'name': '10 мкр', 'slug': '10_mkr', 'id': 13},
        {'name': '11 мкр', 'slug': '11_mkr', 'id': 14},
        {'name': '12 мкр', 'slug': '12_mkr', 'id': 15},
        {'name': 'Мкр Асанбай', 'slug': 'asanbai', 'id': 16},
        {'name': 'Мкр Учкун', 'slug': 'uchkun', 'id': 17},
        {'name': 'Мкр Улан', 'slug': 'ulan', 'id': 18},
        {'name': 'Мкр Тунгуч', 'slug': 'tunguch', 'id': 19},
        {'name': 'Арча-Бешик', 'slug': 'archa_beshik', 'id': 20},
        {'name': 'Ак-Орго', 'slug': 'ak_orgo', 'id': 21},
        {'name': 'Келечек', 'slug': 'kelechek', 'id': 22},
        {'name': 'Кара Жыгач', 'slug': 'kara_gigach', 'id': 23},
        {'name': 'Рабочий городок', 'slug': 'rabochi_gorodok', 'id': 24},
        {'name': 'Керемет', 'slug': 'keremet', 'id': 25},
        {'name': 'Киргизия – 1', 'slug': 'kirgizia_1', 'id': 26},
        {'name': 'Городок строителей', 'slug': 'gorodok_stroitelei', 'id': 27},
        {'name': 'Достук', 'slug': 'dostuk', 'id': 28},
        {'name': 'Пишпек', 'slug': 'pishpek', 'id': 29},
        {'name': 'Ынтымак', 'slug': 'intimak', 'id': 30},
        {'name': 'Жилгородок Совмина', 'slug': 'gilgorodok_sovmina', 'id': 31},
        {'name': 'Лебединовка', 'slug': 'lebedinovka', 'id': 32},
        {'name': 'Алтын Ордо', 'slug': 'altin_ordo', 'id': 33},
        {'name': 'Баят', 'slug': 'baiat', 'id': 34},
        {'name': 'Орто-Сай', 'slug': 'orto_sai', 'id': 35},
        {'name': 'Эне-Сай', 'slug': 'ene_sai', 'id': 36},
        {'name': 'Маевка', 'slug': 'maevka', 'id': 37},
        {'name': 'Пригородное', 'slug': 'prigorodnoe', 'id': 38},
        {'name': 'Беш Кунгей', 'slug': 'besh_kungei', 'id': 39},
        {'name': 'Селекционное', 'slug': 'selectionoe', 'id': 40},
        {'name': 'Ала-Тоо', 'slug': 'ala_too', 'id': 41},
    ]
}


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    def qwerty(apps, schema_editor):
        Region = apps.get_model('locations', 'Region')
        District = apps.get_model('locations', 'District')

        for x in _data['regions']:
            Region.objects.get_or_create(region_id=x['id'], slug=x['slug'], name=x['name'])

        for x in _data['district']:
            District.objects.get_or_create(district_id=x['id'], slug=x['slug'], name=x['name'])


    def revert(apps, scema):
        pass

    operations = [
        migrations.RunPython(qwerty, revert),
    ]
