# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 04:20
from __future__ import unicode_literals

from django.db import migrations


_data = [
    {'name': 'Бишкек', 'slug': 'bishkek', 'id': 1},
    {'name': 'Ош', 'slug': 'osh', 'id': 2},
    {'name': 'Каракол', 'slug': 'karakol', 'id': 3},
    {'name': 'Жалалабат', 'slug': 'zhalalabat', 'id': 4},
    {'name': 'Нарын', 'slug': 'naryn', 'id': 5},
    {'name': 'Токмок', 'slug': 'tokmok', 'id': 6},
    {'name': 'Балыкчи', 'slug': 'balykchi', 'id': 7},
    {'name': 'Кара-Балта', 'slug': 'kara-balta', 'id': 8},
    {'name': 'Талас', 'slug': 'talas', 'id': 9},
    {'name': 'Баткен', 'slug': 'batken', 'id': 10},
    {'name': 'Узген', 'slug': 'uzgen', 'id': 11},
    {'name': 'Кызыл-Кия', 'slug': 'kyzyl-kiia', 'id': 12},
    {'name': 'Чолпон-Ата', 'slug': 'cholpon-ata', 'id': 13},
    {'name': 'Кант', 'slug': 'kant', 'id': 14},
    {'name': 'Исфина', 'slug': 'isfina', 'id': 15},
    {'name': 'Каракуль', 'slug': 'karakul', 'id': 16},
    {'name': 'Кара-Суу', 'slug': 'kara-suu', 'id': 17},
    {'name': 'Таш-Кымыр', 'slug': 'tash-kymyr', 'id': 18},
    {'name': 'Сулюкта', 'slug': 'suliukta', 'id': 19},
    {'name': 'Майли Суу', 'slug': 'maili-suu', 'id': 20},
    {'name': 'Октябрь-1', 'slug': 'oktiabr-1', 'id': 21},
    {'name': 'Токтогул', 'slug': 'toktogul', 'id': 22},
    {'name': 'Орловка', 'slug': 'orlovka', 'id': 23},
]


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city'),
    ]

    def qwerty(apps, schema_editor):
        City = apps.get_model('locations', 'City')

        for x in _data:
            City.objects.get_or_create(city_id=x['id'], slug=x['slug'], name=x['name'])

    def revert(apps, scema):
        pass

    operations = [
        migrations.RunPython(qwerty, revert),
    ]
