# Generated by Django 2.2 on 2020-01-31 08:20

from django.db import migrations, models
import django.db.models.deletion


_data = {
    'regions': [
        {'name': 'Первомайский район', 'slug': 'pervomayskiy-rayon', 'id': 1},
        {'name': 'Свердловский район', 'slug': 'sverdlovskiy-rayon', 'id': 2},
        {'name': 'Октябрьский район', 'slug': 'oktyabrskiy-rayon', 'id': 3},
        {'name': 'Ленинский район', 'slug': 'leninskiy-rayon', 'id': 4},
        {'name': 'Джети-Огузский район', 'slug': 'dzheti-oguzskii-raion', 'id': 10},
        {'name': 'Тонский район', 'slug': 'tonskii-raion', 'id': 11},
        {'name': 'Тюпский район', 'slug': 'tiupskii-raion', 'id': 12},
        {'name': 'Иссык-Кульский район', 'slug': 'issyk-kulskii-raion', 'id': 13},
        {'name': 'Ак-Талинский район', 'slug': 'ak-talinskii-raion', 'id': 14},
        {'name': 'Ат-Башинский район', 'slug': 'at-bashinskii-raion', 'id': 15},
        {'name': 'Жумгальский район', 'slug': 'zhumgalskii-raion', 'id': 16},
        {'name': 'Кочкорский район', 'slug': 'kochkorskii-raion', 'id': 17},
        {'name': 'Нарынский район', 'slug': 'narynskii-raion', 'id': 18},
        {'name': 'Алайский район', 'slug': 'alaiskii-raion', 'id': 19},
        {'name': 'Араванский район', 'slug': 'aravanskii-raion', 'id': 20},
        {'name': 'Кара-Кулджинский район', 'slug': 'kara-kuldzhinskii-raion', 'id': 21},
        {'name': 'Кара-Суйский район', 'slug': 'kara-suiskii-raion', 'id': 22},
        {'name': 'Ноокатский район', 'slug': 'nookatskii-raion', 'id': 23},
        {'name': 'Узгенский район', 'slug': 'uzgenskii-raion', 'id': 24},
        {'name': 'Чон-Алайский район', 'slug': 'chon-alaiskii-raion', 'id': 25},
        {'name': 'Баткенский район', 'slug': 'batkenskii-raion', 'id': 26},
        {'name': 'Кадамжайский район', 'slug': 'kadamzhaiskii-raion', 'id': 27},
        {'name': 'Лейлекский район', 'slug': 'leilekskii-raion', 'id': 28},
        {'name': 'Бакай-Атинский район', 'slug': 'bakai-atinskii-raion', 'id': 29},
        {'name': 'Кара-Бууринский район', 'slug': 'kara-buurinskii-raion', 'id': 30},
        {'name': 'Манасский район', 'slug': 'manasskii-raion', 'id': 31},
        {'name': 'Таласский район', 'slug': 'talasskii-raion', 'id': 32},
        {'name': 'Ак-Суйский район', 'slug': 'ak-suiskii-raion', 'id': 33},
    ],
    'district': [
        {'name': 'Баткенская область', 'slug': 'batkenskaya-oblast', 'id': 2},
        {'name': 'Чуйская область', 'slug': 'chuyskaya-oblast', 'id': 3},
        {'name': 'Джалал-Абадская область', 'slug': 'dzhalal-abadskaya-oblast', 'id': 4},
        {'name': 'Нарынская область', 'slug': 'narynskaya-oblast', 'id': 5},
        {'name': 'Ошская область', 'slug': 'oshskaya-oblast', 'id': 6},
        {'name': 'Таласская область', 'slug': 'talasskaya-oblast', 'id': 7},
        {'name': 'Иссык-Кульская область', 'slug': 'issyk-kulskaya-oblast', 'id': 8},
    ]
}
class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_region_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.District'),
        ),
        # migrations.RunPython(qwerty, revert),

    ]
