# Generated by Django 2.2 on 2020-02-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_region_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.District'),
        ),
    ]
