# Generated by Django 2.2 on 2020-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200131_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('region_id', 'district')},
        ),
    ]
