# Generated by Django 2.2 on 2020-02-19 10:25

from django.db import migrations


DISTRICTS = [
    {'name': 'Бишкек', 'slug': 'bishkek', 'id': 1},
    {'name': 'Ош', 'slug': 'osh', 'id': 2},
    {'name': 'Баткенская область', 'slug': 'batkenskaya-oblast', 'id': 3},
    {'name': 'Чуйская область', 'slug': 'chuyskaya-oblast', 'id': 4},
    {'name': 'Джалал-Абадская область', 'slug': 'dzhalal-abadskaya-oblast', 'id': 5},
    {'name': 'Нарынская область', 'slug': 'narynskaya-oblast', 'id': 6},
    {'name': 'Ошская область', 'slug': 'oshskaya-oblast', 'id': 7},
    {'name': 'Таласская область', 'slug': 'talasskaya-oblast', 'id': 8},
    {'name': 'Иссык-Кульская область', 'slug': 'issyk-kulskaya-oblast', 'id': 9},
]

REGIONS = [
    {'name': 'Первомайский район', 'slug': 'pervomayskiy-rayon', 'id': 1, 'district': 1},
    {'name': 'Свердловский район', 'slug': 'sverdlovskiy-rayon', 'id': 2, 'district': 1},
    {'name': 'Октябрьский район', 'slug': 'oktyabrskiy-rayon', 'id': 3, 'district': 1},
    {'name': 'Ленинский район', 'slug': 'leninskiy-rayon', 'id': 4, 'district': 1},

    {'name': 'Ош', 'slug': 'osh', 'id': 0, 'district': 2},

    {'name': 'Каракол', 'slug': 'karakol', 'id': 1, 'district': 9},
    {'name': 'Балыкчи', 'slug': 'balykchi', 'id': 2, 'district': 9},
    {'name': 'Чолпон-Ата', 'slug': 'cholpon-ata', 'id': 3, 'district': 9},

    {'name': 'Нарын', 'slug': 'naryn', 'id': 1, 'district': 6},

    {'name': 'Токмок', 'slug': 'tokmok', 'id': 1, 'district': 4},
    {'name': 'Кара-Балта', 'slug': 'kara-balta', 'id': 2, 'district': 4},
    {'name': 'Кант', 'slug': 'kant', 'id': 3, 'district': 4},

    {'name': 'Сулюкта', 'slug': 'suliukta', 'id': 1, 'district': 3},
    {'name': 'Исфина', 'slug': 'isfina', 'id': 2, 'district': 3},
    {'name': 'Баткен', 'slug': 'batken', 'id': 3, 'district': 3},
    {'name': 'Кызыл-Кия', 'slug': 'kyzyl-kiia', 'id': 4, 'district': 3},

    {'name': 'Узген', 'slug': 'uzgen', 'id': 1, 'district': 7},
    {'name': 'Кара-Суу', 'slug': 'kara-suu', 'id': 2, 'district': 7},

    {'name': 'Каракуль', 'slug': 'karakul', 'id': 1, 'district': 5},
    {'name': 'Таш-Кымыр', 'slug': 'tash-kymyr', 'id': 2, 'district': 5},
    {'name': 'Жалалабат', 'slug': 'zhalalabat', 'id': 3, 'district': 5},
    {'name': 'Майли Суу', 'slug': 'maili-suu', 'id': 4, 'district': 5},
    {'name': 'Кёк-Джангак', 'slug': 'oktiabr-1', 'id': 5, 'district': 5},
    {'name': 'Токтогул', 'slug': 'toktogul', 'id': 6, 'district': 5},

    {'name': 'Орловка', 'slug': 'orlovka', 'id': 1, 'district': 8},
    {'name': 'Талас', 'slug': 'talas', 'id': 2, 'district': 8},

    {'name': 'Ак-Суйский район', 'slug': 'ak-suiskii-raion', 'id': 33, 'district': 9},
    {'name': 'Джети-Огузский район', 'slug': 'dzheti-oguzskii-raion', 'id': 10, 'district': 9},
    {'name': 'Тонский район', 'slug': 'tonskii-raion', 'id': 11, 'district': 9},
    {'name': 'Тюпский район', 'slug': 'tiupskii-raion', 'id': 12, 'district': 9},
    {'name': 'Иссык-Кульский район', 'slug': 'issyk-kulskii-raion', 'id': 13, 'district': 9},
    {'name': 'Ак-Талинский район', 'slug': 'ak-talinskii-raion', 'id': 14, 'district': 6},
    {'name': 'Ат-Башинский район', 'slug': 'at-bashinskii-raion', 'id': 15, 'district': 6},
    {'name': 'Жумгальский район', 'slug': 'zhumgalskii-raion', 'id': 16, 'district': 6},
    {'name': 'Кочкорский район', 'slug': 'kochkorskii-raion', 'id': 17, 'district': 6},
    {'name': 'Нарынский район', 'slug': 'narynskii-raion', 'id': 18, 'district': 6},
    {'name': 'Алайский район', 'slug': 'alaiskii-raion', 'id': 19, 'district': 7},
    {'name': 'Араванский район', 'slug': 'aravanskii-raion', 'id': 20, 'district': 7},
    {'name': 'Кара-Кулджинский район', 'slug': 'kara-kuldzhinskii-raion', 'id': 21, 'district': 7},
    {'name': 'Кара-Суйский район', 'slug': 'kara-suiskii-raion', 'id': 22, 'district': 7},
    {'name': 'Ноокатский район', 'slug': 'nookatskii-raion', 'id': 23, 'district': 7},
    {'name': 'Узгенский район', 'slug': 'uzgenskii-raion', 'id': 24, 'district': 7},
    {'name': 'Чон-Алайский район', 'slug': 'chon-alaiskii-raion', 'id': 25, 'district': 7},
    {'name': 'Баткенский район', 'slug': 'batkenskii-raion', 'id': 26, 'district': 3},
    {'name': 'Кадамжайский район', 'slug': 'kadamzhaiskii-raion', 'id': 27, 'district': 3},
    {'name': 'Лейлекский район', 'slug': 'leilekskii-raion', 'id': 28, 'district': 3},

    {'name': 'Бакай-Атинский район', 'slug': 'bakai-atinskii-raion', 'id': 29, 'district': 8},
    {'name': 'Кара-Бууринский район', 'slug': 'kara-buurinskii-raion', 'id': 30, 'district': 8},
    {'name': 'Манасский район', 'slug': 'manasskii-raion', 'id': 31, 'district': 8},
    {'name': 'Таласский район', 'slug': 'talasskii-raion', 'id': 32, 'district': 8},
]


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20200219_1025'),
    ]

    def update_district_regions(apps, schema_editor):
        Region = apps.get_model('locations', 'Region')
        District = apps.get_model('locations', 'District')

        District.objects.all().delete()
        Region.objects.all().delete()

        for district in DISTRICTS:
            District.objects.create(
                district_id=district['id'], slug=district['slug'], name=district['name']
            )

        for region in REGIONS:
            Region.objects.create(
                slug=region['slug'], name=region['name'],
                region_id=region['id'], district=District.objects.get(district_id=region['district'])
            )

    def revert(apps, scema):
        pass

    operations = [
        migrations.RunPython(update_district_regions, revert),
    ]
