# Generated by Django 2.2 on 2020-02-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200219_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('district_id',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
    ]
