# Generated by Django 2.2 on 2020-03-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20200220_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('district_id',), 'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(unique=True, verbose_name='Номер области'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='region',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(verbose_name='Номер района'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ЧПУ'),
        ),
    ]
