# Generated by Django 2.2 on 2020-05-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20200529_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('city_id',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
